// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quiik.ABS.Customer.Domain;

public partial class Customers
{
    public int CustomerId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreateDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool IsActive { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }
}