// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Quiik.ABS.Appointment.Domain;

namespace Quiik.ABS.Appointment.Infrastructure;

public partial class ABS_AppointmentsContext : DbContext
{
    public ABS_AppointmentsContext(DbContextOptions<ABS_AppointmentsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Appointments> Appointments { get; set; }

    public virtual DbSet<Tokens> Tokens { get; set; }
    public virtual DbSet<AppointmentConfiguration> AppointmentConfiguration { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppointmentConfiguration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_AppointmentConfiguration");
           
        });
        modelBuilder.Entity<Appointments>(entity =>
        {
            entity.HasKey(e => e.AppointmentId).HasName("PK__Appointm__8ECDFCC238920A07");

            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.DateTime).HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(100);
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Token).WithMany(p => p.Appointments)
                .HasForeignKey(d => d.TokenId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Appointme__Token__35BCFE0A");
        });

        modelBuilder.Entity<Tokens>(entity =>
        {
            entity.HasKey(e => e.TokenId).HasName("PK__Tokens__658FEEEAA10B4E82");

            entity.HasIndex(e => e.TokenNumber, "UQ__Tokens__435734E1C30C3D72").IsUnique();

            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TokenNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}