// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quiik.ABS.Appointment.Domain;

public partial class Appointments
{
    public int AppointmentId { get; set; }

    public int CustomerId { get; set; }

    public DateTime DateTime { get; set; }

    public int TokenId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreateDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool IsActive { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Tokens Token { get; set; }
    public bool IsWeekend()
    {
        return DateTime.DayOfWeek == DayOfWeek.Saturday || DateTime.DayOfWeek == DayOfWeek.Sunday;
    }
}