// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quiik.ABS.Appointment.Domain;

public partial class AppointmentConfiguration
{
    public int Id { get; set; }

    public int MaxPerDay { get; set; }

    public string PrefixToken { get; set; }
}