// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text;

namespace Quiik.ABS.Appointment.Domain;

public partial class Tokens
{
    public int TokenId { get; set; }

    public string TokenNumber { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Appointments> Appointments { get; set; } = new List<Appointments>();

    public string GenerateToken(int length)
    {
        const string AllowedChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        var random = new Random();
        var tokenBuilder = new StringBuilder();

        for (int i = 0; i < length; i++)
        {
            char randomChar = AllowedChars[random.Next(AllowedChars.Length)];
            tokenBuilder.Append(randomChar);
        }

        return tokenBuilder.ToString();
    }
}